name: Windows-RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip -DestinationPath .

    - name: Configure Ngrok
      run: |
        .\ngrok.exe authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        
    - name: Enable TS
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    
    - name: Create Tunnel
      run: .\ngrok.exe tcp 3389 --log=ngrok.log &
      
    - name: Get Public IP
      run: |
        Start-Sleep -Seconds 5
        Invoke-RestMethod -Uri http://localhost:4040/api/tunnels | Select-Object -Expand tunnels | Select-Object -Expand public_url
      
    - name: Keep Alive
      run: |
        $timer = [Diagnostics.Stopwatch]::StartNew()
        while ($timer.Elapsed.TotalHours -lt 6) {
          Write-Host "VM masih aktif. Waktu berlalu: $($timer.Elapsed.TotalHours) jam"
          Start-Sleep -Seconds 300
        }
